bpf:
  masquerade: true

cluster:
  name: k3d-cilium
  id: 99

kubeProxyReplacement: true

hubble:
  enabled: true
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: false
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
  tls:
    auto:
      enabled: true
      method: "helm"
      certValidityDuration: "1095"
  ui:
    enabled: true

ingressController:
  enabled: true
  default: true

authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        server:
          dataStorage:
            enabled: true

encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
  strictMode:
    enabled: false


prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
dashboards:
  enabled: true


# version: 1.17.4
operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
envoy:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
    service:
      type: NodePort
#     # tls:
#     #   authMode: cluster
#     #   server:
#     #     extraDnsNames:
#     #       - "*.{{ cilium_default_domain }}"

ipam:
  mode: kubernetes

externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: "10.0.0.0/9"

monitor:
  # -- Enable the cilium-monitor sidecar.
  enabled: true

# loadBalancer:
#   nodePort:
#     # -- Enable the Cilium NodePort service implementation.
#     enabled: true