apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: uds
servers: 1
agents: 2
image: rancher/k3s:v1.32.5-k3s1
subnet: "10.42.0.0/16"
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
# network: k3d
options:
  k3d:
    wait: true
    timeout: "6m0s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      # Cilium requires network policy and CNI to be turned off
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable servicelb
        nodeFilters:
          - server:*
      - arg: --disable-kube-proxy
        nodeFilters:
          - server:*
      - arg: --cluster-cidr=10.42.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.96.0.0/12
        nodeFilters:
          - server:*