apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: calico
servers: 1
agents: 2
image: rancher/k3s:v1.32.5-k3s1
subnet: "10.42.0.0/16"
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    # nodeLabels:
    #   - label: "node-role.kubernetes.io/worker=true"
    #     nodeFilters:
    #       - agent:*
    extraArgs:
      # Disable default k3s network components to use Calico
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      # Calico specific settings
      - arg: --cluster-cidr=10.42.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=192.168.0.0/16
        nodeFilters:
          - server:*
      # Disable traefik
      - arg: --disable=traefik
        nodeFilters:
          - server:*